export const ADD_ITEM_TO_CART = "ADD_ITEM_TO_CART";
export const REMOVE_CART_ITEM = "REMOVE_CART_ITEM";
export const CART_SAVE_SHIPPING = "CART_SAVE_SHIPPING";
export const CART_SAVE_PAYMENT = "CART_SAVE_PAYMENT";
